name: torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - filelock=3.13.1=py311hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.2=h80987f9_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - idna=3.7=py311hca03da5_0
  - jinja2=3.1.4=py311hca03da5_1
  - joblib=1.4.2=py311hca03da5_0
  - jpeg=9e=h80987f9_3
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxgboost=2.1.1=h313beb8_0
  - lightgbm=4.6.0=py311h313beb8_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py311h80987f9_1
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.2.1=py311hca03da5_0
  - numexpr=2.10.1=py311h5d9532f_0
  - numpy=2.2.1=py311he598dae_0
  - numpy-base=2.2.1=py311hfbfe69c_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.5.0=h81ee809_1
  - pandas=2.2.3=py311hcf29cfe_0
  - pillow=11.0.0=py311h84e58ab_1
  - pip=24.2=py311hca03da5_0
  - py-xgboost=2.1.1=cpu_pyhb442362_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.7=hb885b13_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.11_0
  - pytz=2024.1=py311hca03da5_0
  - pyyaml=6.0.2=py311h80987f9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py311hca03da5_1
  - scikit-learn=1.5.2=py311h313beb8_0
  - scipy=1.14.1=py311hac8794a_0
  - setuptools=72.1.0=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h80987f9_0
  - sympy=1.13.3=py311hca03da5_0
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tk=8.6.14=h6ba3021_0
  - torchaudio=2.5.1=py311_cpu
  - torchvision=0.20.1=py311_cpu
  - typing_extensions=4.12.2=py311hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py311hca03da5_0
  - wheel=0.44.0=py311hca03da5_0
  - xgboost=2.1.1=cpu_pyhb8f9a19_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - biopython==1.85
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pyparsing==3.2.1
      - seaborn==0.13.2
prefix: /opt/anaconda3/envs/torch
